In [1]:
from selenium import webdriver

In [2]:
PATH='driver/chromedriver'

driver=webdriver.Chrome(PATH)

C:\Users\xabie\AppData\Local\Temp\ipykernel_17224\1987694081.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH)

In [3]:
%pip install webdriver-manager

Requirement already satisfied: webdriver-manager in c:\users\xabie\anaconda3\lib\site-packages (3.8.4)
Requirement already satisfied: python-dotenv in c:\users\xabie\anaconda3\lib\site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: requests in c:\users\xabie\anaconda3\lib\site-packages (from webdriver-manager) (2.27.1)
Requirement already satisfied: tqdm in c:\users\xabie\anaconda3\lib\site-packages (from webdriver-manager) (4.64.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\xabie\anaconda3\lib\site-packages (from requests->webdriver-manager) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\xabie\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\xabie\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\xabie\anaconda3\lib\site-packages (from requests->webdriver-manager) (2021.10.8)
Requirement already satisfied: colorama in c:\users\xabie\anaconda3\lib\site-packages (from tqdm->webdriver-manager) (0.4.4)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from webdriver_manager.chrome import ChromeDriverManager

In [5]:
PATH=ChromeDriverManager().install()   # instala el driver

driver=webdriver.Chrome(PATH)         # abre una pestaña de chrome

driver.get('https://www.uefa.com/uefachampionsleague/statistics/clubs/goals/?sortBy=goals')

C:\Users\xabie\AppData\Local\Temp\ipykernel_17224\985294272.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH)         # abre una pestaña de chrome

In [6]:
url="https://www.uefa.com/uefachampionsleague/statistics/clubs/goals/?sortBy=goals"

In [7]:
driver=webdriver.Chrome(PATH)

driver.get(url)

from selenium.webdriver.common.by import By

C:\Users\xabie\AppData\Local\Temp\ipykernel_17224\3296188710.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH)

In [8]:
tabla=driver.find_element(By.TAG_NAME, 'pk-table-body')

filas=tabla.find_elements(By.TAG_NAME, 'pk-table-row')


data=[]*50


for f in filas:
    
    elemen=f.find_elements(By.TAG_NAME, 'pk-table-cell')
    
    tmp=[]
    
    for e in elemen:
        
        tmp.append(e.text)
        
    data.append(tmp)

    
data

[['01\nNapoli\nItaly', '20', '8', '7', '5', '0', '19', '1', '3', '6'],
 ['02\nBayern\nGermany', '18', '12', '3', '2', '0', '15', '2', '0', '6'],
 ['03\nLiverpool\nEngland', '17', '5', '9', '3', '0', '15', '2', '1', '6'],
 ['04\nParis\nFrance', '16', '8', '7', '0', '0', '11', '4', '1', '6'],
 ['04\nBenfica\nPortugal', '16', '7', '4', '3', '0', '12', '3', '3', '6'],
 ['06\nReal Madrid\nSpain', '15', '9', '4', '2', '0', '13', '2', '3', '6'],
 ['07\nMan City\nEngland', '14', '5', '8', '0', '0', '12', '1', '1', '6'],
 ['08\nLeipzig\nGermany', '13', '7', '3', '1', '1', '12', '0', '0', '6'],
 ['09\nPorto\nPortugal', '12', '9', '2', '1', '0', '11', '1', '3', '6'],
 ['09\nBarcelona\nSpain', '12', '4', '5', '3', '0', '11', '1', '0', '6'],
 ['09\nMilan\nItaly', '12', '1', '6', '4', '0', '11', '0', '2', '6'],
 ['12\nAjax\nNetherlands', '11', '3', '6', '2', '0', '11', '0', '1', '6'],
 ['13\nChelsea\nEngland', '10', '6', '4', '0', '0', '8', '2', '1', '6'],
 ['13\nInter\nItaly', '10', '5', '4', '1', '0', '9', '1', '0', '6'],
 ['13\nDortmund\nGermany', '10', '4', '4', '2', '0', '10', '0', '0', '6'],
 ['16\nJuventus\nItaly', '9', '1', '5', '3', '0', '8', '1', '0', '6'],
 ['17\nMarseille\nFrance', '8', '5', '0', '3', '0', '8', '0', '1', '6'],
 ['17\nShakhtar Donetsk\nUkraine',
  '8',
  '3',
  '4',
  '1',
  '0',
  '6',
  '2',
  '0',
  '6'],
 ['17\nTottenham\nEngland', '8', '3', '1', '4', '0', '7', '1', '1', '6'],
 ['17\nSporting CP\nPortugal', '8', '2', '5', '1', '0', '7', '1', '0', '6'],
 ['21\nFrankfurt\nGermany', '7', '5', '1', '1', '0', '7', '0', '1', '6'],
 ['21\nClub Brugge\nBelgium', '7', '3', '3', '1', '0', '7', '0', '1', '6'],
 ['21\nM. Haifa\nIsrael', '7', '0', '4', '2', '1', '7', '0', '1', '6'],
 ['24\nSevilla\nSpain', '6', '2', '0', '4', '0', '6', '0', '0', '6'],
 ['25\nSalzburg\nAustria', '5', '5', '0', '0', '0', '5', '0', '1', '6'],
 ['25\nPlzeň\nCzech Republic', '5', '2', '1', '2', '0', '5', '0', '1', '6'],
 ['25\nAtlético\nSpain', '5', '2', '1', '1', '0', '2', '2', '0', '6'],
 ['28\nLeverkusen\nGermany', '4', '2', '2', '0', '0', '4', '0', '0', '6'],
 ['28\nDinamo Zagreb\nCroatia', '4', '2', '1', '1', '0', '3', '1', '0', '6'],
 ['28\nCeltic\nScotland', '4', '1', '2', '0', '0', '2', '1', '0', '6'],
 ['31\nRangers\nScotland', '2', '2', '0', '0', '0', '1', '1', '1', '6'],
 ['32\nCopenhagen\nDenmark', '1', '1', '0', '0', '0', '1', '0', '0', '6']]

In [9]:
cabeceras=driver.find_element(By.TAG_NAME, 'pk-table-header')

cabeceras=[c.text for c in cabeceras.find_elements(By.TAG_NAME, 'pk-table-header-col')]

driver.quit()

cabeceras

['',
 'Goals',
 'Right foot',
 'Left foot',
 'Other',
 'Goals inside area',
 'Goals outside area',
 'Penalties scored',
 'Matches played',
 'Head']

In [10]:
import pandas as pd

In [11]:
df=pd.DataFrame(data, columns=cabeceras)

df.head(50)

,,Goals,Right foot,Left foot,Other,Goals inside area,Goals outside area,Penalties scored,Matches played,Head
0,01\nNapoli\nItaly,20,8,7,5,0,19,1,3,6
1,02\nBayern\nGermany,18,12,3,2,0,15,2,0,6
2,03\nLiverpool\nEngland,17,5,9,3,0,15,2,1,6
3,04\nParis\nFrance,16,8,7,0,0,11,4,1,6
4,04\nBenfica\nPortugal,16,7,4,3,0,12,3,3,6
5,06\nReal Madrid\nSpain,15,9,4,2,0,13,2,3,6
6,07\nMan City\nEngland,14,5,8,0,0,12,1,1,6
7,08\nLeipzig\nGermany,13,7,3,1,1,12,0,0,6
8,09\nPorto\nPortugal,12,9,2,1,0,11,1,3,6
9,09\nBarcelona\nSpain,12,4,5,3,0,11,1,0,6
10,09\nMilan\nItaly,12,1,6,4,0,11,0,2,6
11,12\nAjax\nNetherlands,11,3,6,2,0,11,0,1,6
12,13\nChelsea\nEngland,10,6,4,0,0,8,2,1,6
13,13\nInter\nItaly,10,5,4,1,0,9,1,0,6
14,13\nDortmund\nGermany,10,4,4,2,0,10,0,0,6
15,16\nJuventus\nItaly,9,1,5,3,0,8,1,0,6
16,17\nMarseille\nFrance,8,5,0,3,0,8,0,1,6
17,17\nShakhtar Donetsk\nUkraine,8,3,4,1,0,6,2,0,6
18,17\nTottenham\nEngland,8,3,1,4,0,7,1,1,6
19,17\nSporting CP\nPortugal,8,2,5,1,0,7,1,0,6
20,21\nFrankfurt\nGermany,7,5,1,1,0,7,0,1,6
21,21\nClub Brugge\nBelgium,7,3,3,1,0,7,0,1,6
22,21\nM. Haifa\nIsrael,7,0,4,2,1,7,0,1,6
23,24\nSevilla\nSpain,6,2,0,4,0,6,0,0,6
24,25\nSalzburg\nAustria,5,5,0,0,0,5,0,1,6
25,25\nPlzeň\nCzech Republic,5,2,1,2,0,5,0,1,6
26,25\nAtlético\nSpain,5,2,1,1,0,2,2,0,6
27,28\nLeverkusen\nGermany,4,2,2,0,0,4,0,0,6
28,28\nDinamo Zagreb\nCroatia,4,2,1,1,0,3,1,0,6
29,28\nCeltic\nScotland,4,1,2,0,0,2,1,0,6
30,31\nRangers\nScotland,2,2,0,0,0,1,1,1,6
31,32\nCopenhagen\nDenmark,1,1,0,0,0,1,0,0,6

In [12]:
df.columns

Index(['', 'Goals', 'Right foot', 'Left foot', 'Other', 'Goals inside area',
       'Goals outside area', 'Penalties scored', 'Matches played', 'Head'],
      dtype='object')

In [13]:
df.columns=['Equipo','Goles', 'Pie_derecho', 'Pie_izquierdo', 'Goles_cabeza', 'Otros','Goles_dentro_area','Goles_fuera_area','Penalties','Partidos_jugados']

df.head(50)

,Equipo,Goles,Pie_derecho,Pie_izquierdo,Goles_cabeza,Otros,Goles_dentro_area,Goles_fuera_area,Penalties,Partidos_jugados
0,01\nNapoli\nItaly,20,8,7,5,0,19,1,3,6
1,02\nBayern\nGermany,18,12,3,2,0,15,2,0,6
2,03\nLiverpool\nEngland,17,5,9,3,0,15,2,1,6
3,04\nParis\nFrance,16,8,7,0,0,11,4,1,6
4,04\nBenfica\nPortugal,16,7,4,3,0,12,3,3,6
5,06\nReal Madrid\nSpain,15,9,4,2,0,13,2,3,6
6,07\nMan City\nEngland,14,5,8,0,0,12,1,1,6
7,08\nLeipzig\nGermany,13,7,3,1,1,12,0,0,6
8,09\nPorto\nPortugal,12,9,2,1,0,11,1,3,6
9,09\nBarcelona\nSpain,12,4,5,3,0,11,1,0,6
10,09\nMilan\nItaly,12,1,6,4,0,11,0,2,6
11,12\nAjax\nNetherlands,11,3,6,2,0,11,0,1,6
12,13\nChelsea\nEngland,10,6,4,0,0,8,2,1,6
13,13\nInter\nItaly,10,5,4,1,0,9,1,0,6
14,13\nDortmund\nGermany,10,4,4,2,0,10,0,0,6
15,16\nJuventus\nItaly,9,1,5,3,0,8,1,0,6
16,17\nMarseille\nFrance,8,5,0,3,0,8,0,1,6
17,17\nShakhtar Donetsk\nUkraine,8,3,4,1,0,6,2,0,6
18,17\nTottenham\nEngland,8,3,1,4,0,7,1,1,6
19,17\nSporting CP\nPortugal,8,2,5,1,0,7,1,0,6
20,21\nFrankfurt\nGermany,7,5,1,1,0,7,0,1,6
21,21\nClub Brugge\nBelgium,7,3,3,1,0,7,0,1,6
22,21\nM. Haifa\nIsrael,7,0,4,2,1,7,0,1,6
23,24\nSevilla\nSpain,6,2,0,4,0,6,0,0,6
24,25\nSalzburg\nAustria,5,5,0,0,0,5,0,1,6
25,25\nPlzeň\nCzech Republic,5,2,1,2,0,5,0,1,6
26,25\nAtlético\nSpain,5,2,1,1,0,2,2,0,6
27,28\nLeverkusen\nGermany,4,2,2,0,0,4,0,0,6
28,28\nDinamo Zagreb\nCroatia,4,2,1,1,0,3,1,0,6
29,28\nCeltic\nScotland,4,1,2,0,0,2,1,0,6
30,31\nRangers\nScotland,2,2,0,0,0,1,1,1,6
31,32\nCopenhagen\nDenmark,1,1,0,0,0,1,0,0,6

In [14]:
df['Equipo']

0                 01\nNapoli\nItaly
1               02\nBayern\nGermany
2            03\nLiverpool\nEngland
3                 04\nParis\nFrance
4             04\nBenfica\nPortugal
5            06\nReal Madrid\nSpain
6             07\nMan City\nEngland
7              08\nLeipzig\nGermany
8               09\nPorto\nPortugal
9              09\nBarcelona\nSpain
10                 09\nMilan\nItaly
11            12\nAjax\nNetherlands
12             13\nChelsea\nEngland
13                 13\nInter\nItaly
14            13\nDortmund\nGermany
15              16\nJuventus\nItaly
16            17\nMarseille\nFrance
17    17\nShakhtar Donetsk\nUkraine
18           17\nTottenham\nEngland
19        17\nSporting CP\nPortugal
20           21\nFrankfurt\nGermany
21         21\nClub Brugge\nBelgium
22             21\nM. Haifa\nIsrael
23               24\nSevilla\nSpain
24            25\nSalzburg\nAustria
25        25\nPlzeň\nCzech Republic
26              25\nAtlético\nSpain
27          28\nLeverkusen\nGermany
28       28\nDinamo Zagreb\nCroatia
29             28\nCeltic\nScotland
30            31\nRangers\nScotland
31          32\nCopenhagen\nDenmark
Name: Equipo, dtype: object

In [15]:
df.Equipo.value_counts()
import numpy as np

In [16]:
df.Equipo.replace(['01\nNapoli\nItaly','02\nBayern\nGermany','03\nLiverpool\nEngland','04\nParis\nFrance','04\nBenfica\nPortugal','06\nReal Madrid\nSpain','07\nMan City\nEngland','08\nLeipzig\nGermany','09\nPorto\nPortugal','09\nBarcelona\nSpain','09\nMilan\nItaly','12\nAjax\nNetherlands','13\nChelsea\nEngland','13\nInter\nItaly','13\nDortmund\nGermany','16\nJuventus\nItaly','17\nMarseille\nFrance','17\nShakhtar Donetsk\nUkraine','17\nTottenham\nEngland','17\nSporting CP\nPortugal','21\nFrankfurt\nGermany','21\nClub Brugge\nBelgium','21\nM. Haifa\nIsrael','24\nSevilla\nSpain','25\nSalzburg\nAustria','25\nPlzeň\nCzech Republic','25\nAtlético\nSpain','28\nLeverkusen\nGermany','28\nDinamo Zagreb\nCroatia','28\nCeltic\nScotland','31\nRangers\nScotland','32\nCopenhagen\nDenmark'], 
                  ['Napoli', 'Bayern','Liverpool','Paris','Benfica','Real Madrid','Man City','Leipzig','Porto','Barcelona','Milan','Ajax','Chelsea','Inter','Dortmund','Juventus','Marseille','Shakhtar Donetsk','Tottenham','Sporting_CP','Frankfurt','Club_Brugge','M_Haifa','Sevilla','Salzburg','Plzeň','Atlético','Leverkusen','Dinamo Zagreb','Celtic','Rangers','Copenhagen'],
                  inplace=True)

df

,Equipo,Goles,Pie_derecho,Pie_izquierdo,Goles_cabeza,Otros,Goles_dentro_area,Goles_fuera_area,Penalties,Partidos_jugados
0,Napoli,20,8,7,5,0,19,1,3,6
1,Bayern,18,12,3,2,0,15,2,0,6
2,Liverpool,17,5,9,3,0,15,2,1,6
3,Paris,16,8,7,0,0,11,4,1,6
4,Benfica,16,7,4,3,0,12,3,3,6
5,Real Madrid,15,9,4,2,0,13,2,3,6
6,Man City,14,5,8,0,0,12,1,1,6
7,Leipzig,13,7,3,1,1,12,0,0,6
8,Porto,12,9,2,1,0,11,1,3,6
9,Barcelona,12,4,5,3,0,11,1,0,6
10,Milan,12,1,6,4,0,11,0,2,6
11,Ajax,11,3,6,2,0,11,0,1,6
12,Chelsea,10,6,4,0,0,8,2,1,6
13,Inter,10,5,4,1,0,9,1,0,6
14,Dortmund,10,4,4,2,0,10,0,0,6
15,Juventus,9,1,5,3,0,8,1,0,6
16,Marseille,8,5,0,3,0,8,0,1,6
17,Shakhtar Donetsk,8,3,4,1,0,6,2,0,6
18,Tottenham,8,3,1,4,0,7,1,1,6
19,Sporting_CP,8,2,5,1,0,7,1,0,6
20,Frankfurt,7,5,1,1,0,7,0,1,6
21,Club_Brugge,7,3,3,1,0,7,0,1,6
22,M_Haifa,7,0,4,2,1,7,0,1,6
23,Sevilla,6,2,0,4,0,6,0,0,6
24,Salzburg,5,5,0,0,0,5,0,1,6
25,Plzeň,5,2,1,2,0,5,0,1,6
26,Atlético,5,2,1,1,0,2,2,0,6
27,Leverkusen,4,2,2,0,0,4,0,0,6
28,Dinamo Zagreb,4,2,1,1,0,3,1,0,6
29,Celtic,4,1,2,0,0,2,1,0,6
30,Rangers,2,2,0,0,0,1,1,1,6
31,Copenhagen,1,1,0,0,0,1,0,0,6

In [17]:
df.insert(1,"Pais",['Italy', 'Germany', 'England','France', 'Portugal', 'Spain', 'England' ,'Germany', 'Portugal' ,'Spain', 'Italy', 'Netherlands', 'England', 'Italy' ,'Germany' ,'Italy', 'France', 'Ukraine', 'England', 'Portugal', 'Germany' ,'Belgium', 'Israel','Spain', 'Austria' ,'Czech_Republic', 'Spain' ,'Germany', 'Croatia', 'Scotland', 'Scotland', 'Denmark'])
df

,Equipo,Pais,Goles,Pie_derecho,Pie_izquierdo,Goles_cabeza,Otros,Goles_dentro_area,Goles_fuera_area,Penalties,Partidos_jugados
0,Napoli,Italy,20,8,7,5,0,19,1,3,6
1,Bayern,Germany,18,12,3,2,0,15,2,0,6
2,Liverpool,England,17,5,9,3,0,15,2,1,6
3,Paris,France,16,8,7,0,0,11,4,1,6
4,Benfica,Portugal,16,7,4,3,0,12,3,3,6
5,Real Madrid,Spain,15,9,4,2,0,13,2,3,6
6,Man City,England,14,5,8,0,0,12,1,1,6
7,Leipzig,Germany,13,7,3,1,1,12,0,0,6
8,Porto,Portugal,12,9,2,1,0,11,1,3,6
9,Barcelona,Spain,12,4,5,3,0,11,1,0,6
10,Milan,Italy,12,1,6,4,0,11,0,2,6
11,Ajax,Netherlands,11,3,6,2,0,11,0,1,6
12,Chelsea,England,10,6,4,0,0,8,2,1,6
13,Inter,Italy,10,5,4,1,0,9,1,0,6
14,Dortmund,Germany,10,4,4,2,0,10,0,0,6
15,Juventus,Italy,9,1,5,3,0,8,1,0,6
16,Marseille,France,8,5,0,3,0,8,0,1,6
17,Shakhtar Donetsk,Ukraine,8,3,4,1,0,6,2,0,6
18,Tottenham,England,8,3,1,4,0,7,1,1,6
19,Sporting_CP,Portugal,8,2,5,1,0,7,1,0,6
20,Frankfurt,Germany,7,5,1,1,0,7,0,1,6
21,Club_Brugge,Belgium,7,3,3,1,0,7,0,1,6
22,M_Haifa,Israel,7,0,4,2,1,7,0,1,6
23,Sevilla,Spain,6,2,0,4,0,6,0,0,6
24,Salzburg,Austria,5,5,0,0,0,5,0,1,6
25,Plzeň,Czech_Republic,5,2,1,2,0,5,0,1,6
26,Atlético,Spain,5,2,1,1,0,2,2,0,6
27,Leverkusen,Germany,4,2,2,0,0,4,0,0,6
28,Dinamo Zagreb,Croatia,4,2,1,1,0,3,1,0,6
29,Celtic,Scotland,4,1,2,0,0,2,1,0,6
30,Rangers,Scotland,2,2,0,0,0,1,1,1,6
31,Copenhagen,Denmark,1,1,0,0,0,1,0,0,6

In [18]:
estadisticas_equipos=df

In [19]:
estadisticas_equipos

,Equipo,Pais,Goles,Pie_derecho,Pie_izquierdo,Goles_cabeza,Otros,Goles_dentro_area,Goles_fuera_area,Penalties,Partidos_jugados
0,Napoli,Italy,20,8,7,5,0,19,1,3,6
1,Bayern,Germany,18,12,3,2,0,15,2,0,6
2,Liverpool,England,17,5,9,3,0,15,2,1,6
3,Paris,France,16,8,7,0,0,11,4,1,6
4,Benfica,Portugal,16,7,4,3,0,12,3,3,6
5,Real Madrid,Spain,15,9,4,2,0,13,2,3,6
6,Man City,England,14,5,8,0,0,12,1,1,6
7,Leipzig,Germany,13,7,3,1,1,12,0,0,6
8,Porto,Portugal,12,9,2,1,0,11,1,3,6
9,Barcelona,Spain,12,4,5,3,0,11,1,0,6
10,Milan,Italy,12,1,6,4,0,11,0,2,6
11,Ajax,Netherlands,11,3,6,2,0,11,0,1,6
12,Chelsea,England,10,6,4,0,0,8,2,1,6
13,Inter,Italy,10,5,4,1,0,9,1,0,6
14,Dortmund,Germany,10,4,4,2,0,10,0,0,6
15,Juventus,Italy,9,1,5,3,0,8,1,0,6
16,Marseille,France,8,5,0,3,0,8,0,1,6
17,Shakhtar Donetsk,Ukraine,8,3,4,1,0,6,2,0,6
18,Tottenham,England,8,3,1,4,0,7,1,1,6
19,Sporting_CP,Portugal,8,2,5,1,0,7,1,0,6
20,Frankfurt,Germany,7,5,1,1,0,7,0,1,6
21,Club_Brugge,Belgium,7,3,3,1,0,7,0,1,6
22,M_Haifa,Israel,7,0,4,2,1,7,0,1,6
23,Sevilla,Spain,6,2,0,4,0,6,0,0,6
24,Salzburg,Austria,5,5,0,0,0,5,0,1,6
25,Plzeň,Czech_Republic,5,2,1,2,0,5,0,1,6
26,Atlético,Spain,5,2,1,1,0,2,2,0,6
27,Leverkusen,Germany,4,2,2,0,0,4,0,0,6
28,Dinamo Zagreb,Croatia,4,2,1,1,0,3,1,0,6
29,Celtic,Scotland,4,1,2,0,0,2,1,0,6
30,Rangers,Scotland,2,2,0,0,0,1,1,1,6
31,Copenhagen,Denmark,1,1,0,0,0,1,0,0,6

In [20]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from urllib.request import urlopen
pd.set_option('display.max_columns', None)
estadisticas_equipos.to_csv('../proyectototal/Val2', index=False)

In [21]:
%pip install mysql-connector-python
%pip install SQLAlchemy

Requirement already satisfied: mysql-connector-python in c:\users\xabie\anaconda3\lib\site-packages (8.0.31)
Requirement already satisfied: protobuf<=3.20.1,>=3.11.0 in c:\users\xabie\anaconda3\lib\site-packages (from mysql-connector-python) (3.19.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: SQLAlchemy in c:\users\xabie\anaconda3\lib\site-packages (1.4.32)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\xabie\anaconda3\lib\site-packages (from SQLAlchemy) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [22]:
from sqlalchemy import create_engine

In [23]:
import mysql.connector as conn

In [24]:
str_conn='mysql+pymysql://root:password@localhost:3306'

cursor=create_engine(str_conn)

cursor.execute('drop database if exists Champions_league;')

cursor.execute('create database Champions_league;')

In [25]:
str_conn='mysql+pymysql://root:password@localhost:3306/Champions_league'

cursor=create_engine(str_conn)

In [26]:
estadisticas_equipos.to_sql(name='estadisticas_equipos', con=cursor, if_exists='replace', index=False)

32